# Generated by Django 3.2.23 on 2024-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField(null=True)),
                ('gender', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=100)),
                ('phonenumber', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=255)),
                ('nationality', models.CharField(default='', max_length=255)),
                ('maritalstatus', models.CharField(default='', max_length=255)),
                ('occupation', models.CharField(default='', max_length=255)),
                ('emergencycontact', models.CharField(default='', max_length=255)),
                ('insuranceinformation', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
